// const sidebars: SidebarsConfig = {
// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Get Started",
      items: [
        "Introduction", // Ensure this matches the document ID
      ],
      className: "my-4 text-base font-semibold ", // Added responsive padding-right
    },
    {
      type: "category",
      label: "Super Admin",
      items: [
        "Super Admin/Dashboard",
        "Super Admin/Map",
        "Super Admin/Alert",
        "Super Admin/Regions",
        "Super Admin/Control Room Users",
        "Super Admin/Sites",
        "Super Admin/Captains",
        "Super Admin/SMS Templates",
        "Super Admin/Emails Templates",
        "Super Admin/Site Types",
        "Super Admin/Alert Types",
      ],
      className: "my-4 text-base font-semibold ", // Added responsive padding-right
    },
    {
      type: "category",
      label: "Regional Admin",
      items: [
        "Regional Admin/Dashboard",
        "Regional Admin/Map",
        "Regional Admin/Alert",
        "Regional Admin/Sites",
        "Regional Admin/Captains",
      ],
      className: "my-4 text-base font-semibold ", // Added responsive padding-right
    },
  ],
};

export default sidebars;
